namespace HtmlWebParser.Elements
{
    public abstract class EventHandler
    {
        public string onabort;
        public string onautocomplete;
        public string onautocompleteerror;
        public string onblur;
        public string oncancel;
        public string oncanplay;
        public string oncanplaythrough;
        public string onchange;
        public string onclick;
        public string onclose;
        public string oncontextmenu;
        public string oncuechange;
        public string ondblclick;
        public string ondrag;
        public string ondragend;
        public string ondragenter;
        public string ondragexit;
        public string ondragleave;
        public string ondragover;
        public string ondragstart;
        public string ondrop;
        public string ondurationchange;
        public string onemptied;
        public string onended;
        public string onerror;
        public string onfocus;
        public string oninput;
        public string oninvalid;
        public string onkeydown;
        public string onkeypress;
        public string onkeyup;
        public string onload;
        public string onloadeddata;
        public string onloadedmetadata;
        public string onloadstart;
        public string onmousedown;
        public string onmouseenter;
        public string onmouseleave;
        public string onmousemove;
        public string onmouseout;
        public string onmouseover;
        public string onmouseup;
        public string onmousewheel;
        public string onpause;
        public string onplay;
        public string onplaying;
        public string onprogress;
        public string onratechange;
        public string onreset;
        public string onresize;
        public string onscroll;
        public string onseeked;
        public string onseeking;
        public string onselect;
        public string onshow;
        public string onsort;
        public string onstalled;
        public string onsubmit;
        public string onsuspend;
        public string ontimeupdate;
        public string ontoggle;
        public string onvolumechange;
        public string onwaiting;
    }
}